FROM openjdk:8-jre

ADD target/kafka-producer-twitter-1.0-SNAPSHOT-jar-with-dependencies.jar /opt/kafka-producer-twitter-1.0-SNAPSHOT-jar-with-dependencies.jar

CMD ["java", "-cp", "/opt/kafka-beginners-course-1.0-SNAPSHOT-jar-with-dependencies.jar", "kafka.tutorial2.TwitterProducer"]
